In [2]:
import pandas as pd
df = pd.read_csv("data.csv")

In [3]:
df.isnull() #true = valeur vide

,id,date,first_name,last_name,email,gender,ip_address,country,price_paid,tax
0,False,False,False,False,False,False,False,False,False,True
1,False,False,False,False,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,True
996,False,False,False,False,False,False,False,True,False,False
997,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,True
999,False,False,False,False,False,True,False,False,False,False